inherit_from: rubocop-todo.yml

AllCops:
  Exclude:
    - 'config/**/*'
    - 'spec/dummy/config/**/*'
    - 'db/**/*'
    - 'spec/dummy/db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.2

# Use UTF-8 as the source file encoding.
Encoding:
  Enabled: false

# Limit lines to 80 characters.
LineLength:
  Max: 120

AndOr:
  Enabled: false

MethodLength:
  CountComments: false  # count full line comments?
  Max: 30

# Limit modules to have a length of 200
Metrics/ModuleLength:
  Max: 200
  
# Limit classes to have a length of 200
Metrics/ClassLength:
  Max: 200

################################################################## DISABLED COPS
# These cops are disabled because we think they are a Bad Idea. If you add one
# here, make sure to add a comment describing what the cop does, and why this
# is a bad idea.

# Forces the argument names of the block given to #reduce to be `a, e`. Only
# applies on single-line blocks, but why would we want to force people to use
# less descriptive names?
Documentation:
  Enabled: false

